package com.evosnap.schemas.cws.v2_0.serviceinformation;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-21T11:20:06.916-07:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "CWSServiceInformation", 
                  wsdlLocation = "WS/SIS/CwsServiceInformation.wsdl",
                  targetNamespace = "http://schemas.evosnap.com/CWS/v2.0/ServiceInformation") 
public class CWSServiceInformation extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://schemas.evosnap.com/CWS/v2.0/ServiceInformation", "CWSServiceInformation");
    public final static QName ServiceInfoProcessingICWSServiceInformation = new QName("http://schemas.evosnap.com/CWS/v2.0/ServiceInformation", "ServiceInfoProcessing_ICWSServiceInformation");
    static {
        URL url = CWSServiceInformation.class.getResource("WS/SIS/CwsServiceInformation.wsdl");
        if (url == null) {
            url = CWSServiceInformation.class.getClassLoader().getResource("WS/SIS/CwsServiceInformation.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(CWSServiceInformation.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "WS/SIS/CwsServiceInformation.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public CWSServiceInformation(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CWSServiceInformation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CWSServiceInformation() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CWSServiceInformation(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CWSServiceInformation(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CWSServiceInformation(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ICWSServiceInformation
     */
    @WebEndpoint(name = "ServiceInfoProcessing_ICWSServiceInformation")
    public ICWSServiceInformation getServiceInfoProcessingICWSServiceInformation() {
        return super.getPort(ServiceInfoProcessingICWSServiceInformation, ICWSServiceInformation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICWSServiceInformation
     */
    @WebEndpoint(name = "ServiceInfoProcessing_ICWSServiceInformation")
    public ICWSServiceInformation getServiceInfoProcessingICWSServiceInformation(WebServiceFeature... features) {
        return super.getPort(ServiceInfoProcessingICWSServiceInformation, ICWSServiceInformation.class, features);
    }

}
