
package com.evosnap.schemas.cws.v2_0.serviceinformation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-21T11:20:06.345-07:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "BadAttemptThresholdExceededFault", targetNamespace = "http://schemas.evosnap.com/Identity/1.0/")
public class ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyBadAttemptThresholdExceededFaultFaultFaultMessage extends Exception {
    
    private com.evosnap.schemas.identity._1.BadAttemptThresholdExceededFault badAttemptThresholdExceededFault;

    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyBadAttemptThresholdExceededFaultFaultFaultMessage() {
        super();
    }
    
    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyBadAttemptThresholdExceededFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyBadAttemptThresholdExceededFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyBadAttemptThresholdExceededFaultFaultFaultMessage(String message, com.evosnap.schemas.identity._1.BadAttemptThresholdExceededFault badAttemptThresholdExceededFault) {
        super(message);
        this.badAttemptThresholdExceededFault = badAttemptThresholdExceededFault;
    }

    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyBadAttemptThresholdExceededFaultFaultFaultMessage(String message, com.evosnap.schemas.identity._1.BadAttemptThresholdExceededFault badAttemptThresholdExceededFault, Throwable cause) {
        super(message, cause);
        this.badAttemptThresholdExceededFault = badAttemptThresholdExceededFault;
    }

    public com.evosnap.schemas.identity._1.BadAttemptThresholdExceededFault getFaultInfo() {
        return this.badAttemptThresholdExceededFault;
    }
}
