
package com.evosnap.schemas.cws.v2_0.serviceinformation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-21T11:20:06.529-07:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "GeneratePasswordFault", targetNamespace = "http://schemas.evosnap.com/Identity/1.0/")
public class ICWSServiceInformationResetPasswordForServiceKeyGeneratePasswordFaultFaultFaultMessage extends Exception {
    
    private com.evosnap.schemas.identity._1.GeneratePasswordFault generatePasswordFault;

    public ICWSServiceInformationResetPasswordForServiceKeyGeneratePasswordFaultFaultFaultMessage() {
        super();
    }
    
    public ICWSServiceInformationResetPasswordForServiceKeyGeneratePasswordFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ICWSServiceInformationResetPasswordForServiceKeyGeneratePasswordFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ICWSServiceInformationResetPasswordForServiceKeyGeneratePasswordFaultFaultFaultMessage(String message, com.evosnap.schemas.identity._1.GeneratePasswordFault generatePasswordFault) {
        super(message);
        this.generatePasswordFault = generatePasswordFault;
    }

    public ICWSServiceInformationResetPasswordForServiceKeyGeneratePasswordFaultFaultFaultMessage(String message, com.evosnap.schemas.identity._1.GeneratePasswordFault generatePasswordFault, Throwable cause) {
        super(message, cause);
        this.generatePasswordFault = generatePasswordFault;
    }

    public com.evosnap.schemas.identity._1.GeneratePasswordFault getFaultInfo() {
        return this.generatePasswordFault;
    }
}
