
package com.evosnap.schemas.cws.v2_0.serviceinformation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-21T11:20:06.335-07:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "OneTimePasswordFault", targetNamespace = "http://schemas.evosnap.com/Identity/1.0/")
public class ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyOneTimePasswordFaultFaultFaultMessage extends Exception {
    
    private com.evosnap.schemas.identity._1.OneTimePasswordFault oneTimePasswordFault;

    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyOneTimePasswordFaultFaultFaultMessage() {
        super();
    }
    
    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyOneTimePasswordFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyOneTimePasswordFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyOneTimePasswordFaultFaultFaultMessage(String message, com.evosnap.schemas.identity._1.OneTimePasswordFault oneTimePasswordFault) {
        super(message);
        this.oneTimePasswordFault = oneTimePasswordFault;
    }

    public ICWSServiceInformationSignOnWithUsernamePasswordForServiceKeyOneTimePasswordFaultFaultFaultMessage(String message, com.evosnap.schemas.identity._1.OneTimePasswordFault oneTimePasswordFault, Throwable cause) {
        super(message, cause);
        this.oneTimePasswordFault = oneTimePasswordFault;
    }

    public com.evosnap.schemas.identity._1.OneTimePasswordFault getFaultInfo() {
        return this.oneTimePasswordFault;
    }
}
