
package com.evosnap.schemas.cws.v2_0.serviceinformation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-21T11:20:06.608-07:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "InvalidEmailFault", targetNamespace = "http://schemas.evosnap.com/Identity/1.0/")
public class ICWSServiceInformationChangeEmailForServiceKeyInvalidEmailFaultFaultFaultMessage extends Exception {
    
    private com.evosnap.schemas.identity._1.InvalidEmailFault invalidEmailFault;

    public ICWSServiceInformationChangeEmailForServiceKeyInvalidEmailFaultFaultFaultMessage() {
        super();
    }
    
    public ICWSServiceInformationChangeEmailForServiceKeyInvalidEmailFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ICWSServiceInformationChangeEmailForServiceKeyInvalidEmailFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ICWSServiceInformationChangeEmailForServiceKeyInvalidEmailFaultFaultFaultMessage(String message, com.evosnap.schemas.identity._1.InvalidEmailFault invalidEmailFault) {
        super(message);
        this.invalidEmailFault = invalidEmailFault;
    }

    public ICWSServiceInformationChangeEmailForServiceKeyInvalidEmailFaultFaultFaultMessage(String message, com.evosnap.schemas.identity._1.InvalidEmailFault invalidEmailFault, Throwable cause) {
        super(message, cause);
        this.invalidEmailFault = invalidEmailFault;
    }

    public com.evosnap.schemas.identity._1.InvalidEmailFault getFaultInfo() {
        return this.invalidEmailFault;
    }
}
