
package com.evosnap.schemas.cws.v2_0.serviceinformation;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-21T11:20:06.750-07:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "PasswordInvalidFault", targetNamespace = "http://schemas.evosnap.com/Identity/1.0/")
public class ICWSServiceInformationChangePasswordForServiceKeyPasswordInvalidFaultFaultFaultMessage extends Exception {
    
    private com.evosnap.schemas.identity._1.PasswordInvalidFault passwordInvalidFault;

    public ICWSServiceInformationChangePasswordForServiceKeyPasswordInvalidFaultFaultFaultMessage() {
        super();
    }
    
    public ICWSServiceInformationChangePasswordForServiceKeyPasswordInvalidFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ICWSServiceInformationChangePasswordForServiceKeyPasswordInvalidFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ICWSServiceInformationChangePasswordForServiceKeyPasswordInvalidFaultFaultFaultMessage(String message, com.evosnap.schemas.identity._1.PasswordInvalidFault passwordInvalidFault) {
        super(message);
        this.passwordInvalidFault = passwordInvalidFault;
    }

    public ICWSServiceInformationChangePasswordForServiceKeyPasswordInvalidFaultFaultFaultMessage(String message, com.evosnap.schemas.identity._1.PasswordInvalidFault passwordInvalidFault, Throwable cause) {
        super(message, cause);
        this.passwordInvalidFault = passwordInvalidFault;
    }

    public com.evosnap.schemas.identity._1.PasswordInvalidFault getFaultInfo() {
        return this.passwordInvalidFault;
    }
}
