package com.evosnap.schemas.cws.v2_0.transactionprocessing;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-22T08:57:23.561-07:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "CwsTransactionProcessing", 
                  wsdlLocation = "WS/TXN/CwsTransactionProcessing.wsdl",
                  targetNamespace = "http://schemas.evosnap.com/CWS/v2.0/TransactionProcessing") 
public class CwsTransactionProcessing extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://schemas.evosnap.com/CWS/v2.0/TransactionProcessing", "CwsTransactionProcessing");
    public final static QName TransactionProcessingICwsTransactionProcessing = new QName("http://schemas.evosnap.com/CWS/v2.0/TransactionProcessing", "TransactionProcessing_ICwsTransactionProcessing");
    static {
        URL url = CwsTransactionProcessing.class.getResource("WS/TXN/CwsTransactionProcessing.wsdl");
        if (url == null) {
            url = CwsTransactionProcessing.class.getClassLoader().getResource("WS/TXN/CwsTransactionProcessing.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(CwsTransactionProcessing.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "WS/TXN/CwsTransactionProcessing.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public CwsTransactionProcessing(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CwsTransactionProcessing(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CwsTransactionProcessing() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CwsTransactionProcessing(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CwsTransactionProcessing(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CwsTransactionProcessing(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ICwsTransactionProcessing
     */
    @WebEndpoint(name = "TransactionProcessing_ICwsTransactionProcessing")
    public ICwsTransactionProcessing getTransactionProcessingICwsTransactionProcessing() {
        return super.getPort(TransactionProcessingICwsTransactionProcessing, ICwsTransactionProcessing.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICwsTransactionProcessing
     */
    @WebEndpoint(name = "TransactionProcessing_ICwsTransactionProcessing")
    public ICwsTransactionProcessing getTransactionProcessingICwsTransactionProcessing(WebServiceFeature... features) {
        return super.getPort(TransactionProcessingICwsTransactionProcessing, ICwsTransactionProcessing.class, features);
    }

}
