
package com.evosnap.schemas.cws.v2_0.transactionprocessing;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-22T08:57:22.195-07:00
 * Generated source version: 2.7.7
 * 
 */
public final class ICwsTransactionProcessing_TransactionProcessingICwsTransactionProcessing_Client {

    private static final QName SERVICE_NAME = new QName("http://schemas.evosnap.com/CWS/v2.0/TransactionProcessing", "CwsTransactionProcessing");

    private ICwsTransactionProcessing_TransactionProcessingICwsTransactionProcessing_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CwsTransactionProcessing.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CwsTransactionProcessing ss = new CwsTransactionProcessing(wsdlURL, SERVICE_NAME);
        ICwsTransactionProcessing port = ss.getTransactionProcessingICwsTransactionProcessing();  
        
        {
        System.out.println("Invoking authorize...");
        java.lang.String _authorize_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.Transaction _authorize_transaction = null;
        java.lang.String _authorize_applicationProfileId = "";
        java.lang.String _authorize_merchantProfileId = "";
        java.lang.String _authorize_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _authorize__return = port.authorize(_authorize_sessionToken, _authorize_transaction, _authorize_applicationProfileId, _authorize_merchantProfileId, _authorize_workflowId);
            System.out.println("authorize.result=" + _authorize__return);

        } catch (ICwsTransactionProcessingAuthorizeCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Authorize_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking ping...");
        com.evosnap.schemas.ipc_general_wcf_contracts_common.external.PingResponse _ping__return = port.ping();
        System.out.println("ping.result=" + _ping__return);


        }
        {
        System.out.println("Invoking manageAccount...");
        java.lang.String _manageAccount_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.Transaction _manageAccount_transaction = null;
        java.lang.String _manageAccount_applicationProfileId = "";
        java.lang.String _manageAccount_merchantProfileId = "";
        java.lang.String _manageAccount_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _manageAccount__return = port.manageAccount(_manageAccount_sessionToken, _manageAccount_transaction, _manageAccount_applicationProfileId, _manageAccount_merchantProfileId, _manageAccount_workflowId);
            System.out.println("manageAccount.result=" + _manageAccount__return);

        } catch (ICwsTransactionProcessingManageAccountCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccount_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking manageAccountById...");
        java.lang.String _manageAccountById_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.Manage _manageAccountById_differenceData = null;
        java.lang.String _manageAccountById_applicationProfileId = "";
        java.lang.String _manageAccountById_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _manageAccountById__return = port.manageAccountById(_manageAccountById_sessionToken, _manageAccountById_differenceData, _manageAccountById_applicationProfileId, _manageAccountById_workflowId);
            System.out.println("manageAccountById.result=" + _manageAccountById__return);

        } catch (ICwsTransactionProcessingManageAccountByIdCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingManageAccountByIdCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ManageAccountById_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking returnUnlinked...");
        java.lang.String _returnUnlinked_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.Transaction _returnUnlinked_transaction = null;
        java.lang.String _returnUnlinked_applicationProfileId = "";
        java.lang.String _returnUnlinked_merchantProfileId = "";
        java.lang.String _returnUnlinked_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _returnUnlinked__return = port.returnUnlinked(_returnUnlinked_sessionToken, _returnUnlinked_transaction, _returnUnlinked_applicationProfileId, _returnUnlinked_merchantProfileId, _returnUnlinked_workflowId);
            System.out.println("returnUnlinked.result=" + _returnUnlinked__return);

        } catch (ICwsTransactionProcessingReturnUnlinkedCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnUnlinkedCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnUnlinked_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking verify...");
        java.lang.String _verify_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.Transaction _verify_transaction = null;
        java.lang.String _verify_applicationProfileId = "";
        java.lang.String _verify_merchantProfileId = "";
        java.lang.String _verify_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _verify__return = port.verify(_verify_sessionToken, _verify_transaction, _verify_applicationProfileId, _verify_merchantProfileId, _verify_workflowId);
            System.out.println("verify.result=" + _verify__return);

        } catch (ICwsTransactionProcessingVerifyCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingVerifyCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Verify_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking capture...");
        java.lang.String _capture_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.Capture _capture_differenceData = null;
        java.lang.String _capture_applicationProfileId = "";
        java.lang.String _capture_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _capture__return = port.capture(_capture_sessionToken, _capture_differenceData, _capture_applicationProfileId, _capture_workflowId);
            System.out.println("capture.result=" + _capture__return);

        } catch (ICwsTransactionProcessingCaptureCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Capture_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking captureSelective...");
        java.lang.String _captureSelective_sessionToken = "";
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring _captureSelective_transactionIds = null;
        com.evosnap.schemas.cws.v2_0.transactions.ArrayOfCapture _captureSelective_differenceData = null;
        java.lang.String _captureSelective_applicationProfileId = "";
        java.lang.String _captureSelective_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.ArrayOfResponse _captureSelective__return = port.captureSelective(_captureSelective_sessionToken, _captureSelective_transactionIds, _captureSelective_differenceData, _captureSelective_applicationProfileId, _captureSelective_workflowId);
            System.out.println("captureSelective.result=" + _captureSelective__return);

        } catch (ICwsTransactionProcessingCaptureSelectiveCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelective_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking returnById...");
        java.lang.String _returnById_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.Return _returnById_differenceData = null;
        java.lang.String _returnById_applicationProfileId = "";
        java.lang.String _returnById_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _returnById__return = port.returnById(_returnById_sessionToken, _returnById_differenceData, _returnById_applicationProfileId, _returnById_workflowId);
            System.out.println("returnById.result=" + _returnById__return);

        } catch (ICwsTransactionProcessingReturnByIdCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingReturnByIdCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_ReturnById_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking captureAll...");
        java.lang.String _captureAll_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.ArrayOfCapture _captureAll_differenceData = null;
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring _captureAll_batchIds = null;
        java.lang.String _captureAll_applicationProfileId = "";
        java.lang.String _captureAll_merchantProfileId = "";
        java.lang.String _captureAll_workflowId = "";
        java.lang.Boolean _captureAll_forceClose = null;
        try {
            com.evosnap.schemas.cws.v2_0.transactions.ArrayOfResponse _captureAll__return = port.captureAll(_captureAll_sessionToken, _captureAll_differenceData, _captureAll_batchIds, _captureAll_applicationProfileId, _captureAll_merchantProfileId, _captureAll_workflowId, _captureAll_forceClose);
            System.out.println("captureAll.result=" + _captureAll__return);

        } catch (ICwsTransactionProcessingCaptureAllCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAll_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking acknowledge...");
        java.lang.String _acknowledge_sessionToken = "";
        java.lang.String _acknowledge_transactionId = "";
        java.lang.String _acknowledge_applicationProfileId = "";
        java.lang.String _acknowledge_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _acknowledge__return = port.acknowledge(_acknowledge_sessionToken, _acknowledge_transactionId, _acknowledge_applicationProfileId, _acknowledge_workflowId);
            System.out.println("acknowledge.result=" + _acknowledge__return);

        } catch (ICwsTransactionProcessingAcknowledgeCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAcknowledgeCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Acknowledge_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking disburse...");
        java.lang.String _disburse_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.Transaction _disburse_transaction = null;
        java.lang.String _disburse_applicationProfileId = "";
        java.lang.String _disburse_merchantProfileId = "";
        java.lang.String _disburse_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _disburse__return = port.disburse(_disburse_sessionToken, _disburse_transaction, _disburse_applicationProfileId, _disburse_merchantProfileId, _disburse_workflowId);
            System.out.println("disburse.result=" + _disburse__return);

        } catch (ICwsTransactionProcessingDisburseCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingDisburseCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Disburse_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking authorizeAndCapture...");
        java.lang.String _authorizeAndCapture_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.Transaction _authorizeAndCapture_transaction = null;
        java.lang.String _authorizeAndCapture_applicationProfileId = "";
        java.lang.String _authorizeAndCapture_merchantProfileId = "";
        java.lang.String _authorizeAndCapture_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _authorizeAndCapture__return = port.authorizeAndCapture(_authorizeAndCapture_sessionToken, _authorizeAndCapture_transaction, _authorizeAndCapture_applicationProfileId, _authorizeAndCapture_merchantProfileId, _authorizeAndCapture_workflowId);
            System.out.println("authorizeAndCapture.result=" + _authorizeAndCapture__return);

        } catch (ICwsTransactionProcessingAuthorizeAndCaptureCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAuthorizeAndCaptureCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_AuthorizeAndCapture_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking queryAccount...");
        java.lang.String _queryAccount_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.Transaction _queryAccount_transaction = null;
        java.lang.String _queryAccount_applicationProfileId = "";
        java.lang.String _queryAccount_merchantProfileId = "";
        java.lang.String _queryAccount_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _queryAccount__return = port.queryAccount(_queryAccount_sessionToken, _queryAccount_transaction, _queryAccount_applicationProfileId, _queryAccount_merchantProfileId, _queryAccount_workflowId);
            System.out.println("queryAccount.result=" + _queryAccount__return);

        } catch (ICwsTransactionProcessingQueryAccountCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingQueryAccountCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_QueryAccount_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking captureSelectiveAsync...");
        java.lang.String _captureSelectiveAsync_sessionToken = "";
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring _captureSelectiveAsync_transactionIds = null;
        com.evosnap.schemas.cws.v2_0.transactions.ArrayOfCapture _captureSelectiveAsync_differenceData = null;
        java.lang.String _captureSelectiveAsync_applicationProfileId = "";
        java.lang.String _captureSelectiveAsync_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _captureSelectiveAsync__return = port.captureSelectiveAsync(_captureSelectiveAsync_sessionToken, _captureSelectiveAsync_transactionIds, _captureSelectiveAsync_differenceData, _captureSelectiveAsync_applicationProfileId, _captureSelectiveAsync_workflowId);
            System.out.println("captureSelectiveAsync.result=" + _captureSelectiveAsync__return);

        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureSelectiveAsyncCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureSelectiveAsync_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking undo...");
        java.lang.String _undo_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.Undo _undo_differenceData = null;
        java.lang.String _undo_applicationProfileId = "";
        java.lang.String _undo_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _undo__return = port.undo(_undo_sessionToken, _undo_differenceData, _undo_applicationProfileId, _undo_workflowId);
            System.out.println("undo.result=" + _undo__return);

        } catch (ICwsTransactionProcessingUndoCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingUndoCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Undo_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking adjust...");
        java.lang.String _adjust_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.Adjust _adjust_differenceData = null;
        java.lang.String _adjust_applicationProfileId = "";
        java.lang.String _adjust_workflowId = "";
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _adjust__return = port.adjust(_adjust_sessionToken, _adjust_differenceData, _adjust_applicationProfileId, _adjust_workflowId);
            System.out.println("adjust.result=" + _adjust__return);

        } catch (ICwsTransactionProcessingAdjustCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingAdjustCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_Adjust_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking captureAllAsync...");
        java.lang.String _captureAllAsync_sessionToken = "";
        com.evosnap.schemas.cws.v2_0.transactions.ArrayOfCapture _captureAllAsync_differenceData = null;
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring _captureAllAsync_batchIds = null;
        java.lang.String _captureAllAsync_applicationProfileId = "";
        java.lang.String _captureAllAsync_merchantProfileId = "";
        java.lang.String _captureAllAsync_workflowId = "";
        java.lang.Boolean _captureAllAsync_forceClose = null;
        try {
            com.evosnap.schemas.cws.v2_0.transactions.Response _captureAllAsync__return = port.captureAllAsync(_captureAllAsync_sessionToken, _captureAllAsync_differenceData, _captureAllAsync_batchIds, _captureAllAsync_applicationProfileId, _captureAllAsync_merchantProfileId, _captureAllAsync_workflowId, _captureAllAsync_forceClose);
            System.out.println("captureAllAsync.result=" + _captureAllAsync__return);

        } catch (ICwsTransactionProcessingCaptureAllAsyncCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingCaptureAllAsyncCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_CaptureAllAsync_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking requestTransaction...");
        java.lang.String _requestTransaction_sessionToken = "";
        java.lang.String _requestTransaction_merchantProfileId = "";
        com.evosnap.schemas.cws.v2_0.transactions.TransactionTenderData _requestTransaction_tenderData = null;
        try {
            com.evosnap.schemas.cws.v2_0.transactions.ArrayOfResponse _requestTransaction__return = port.requestTransaction(_requestTransaction_sessionToken, _requestTransaction_merchantProfileId, _requestTransaction_tenderData);
            System.out.println("requestTransaction.result=" + _requestTransaction__return);

        } catch (ICwsTransactionProcessingRequestTransactionCWSInvalidOperationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_CWSInvalidOperationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionCWSTransactionServiceUnavailableFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_CWSTransactionServiceUnavailableFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionCWSTransactionAlreadySettledFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_CWSTransactionAlreadySettledFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionAuthenticationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_AuthenticationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionCWSTransactionFailedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_CWSTransactionFailedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionCWSOperationNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_CWSOperationNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionExpiredTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_ExpiredTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionCWSConnectionFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_CWSConnectionFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionCWSFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_CWSFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionCWSExtendedDataNotSupportedFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_CWSExtendedDataNotSupportedFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionCWSValidationResultFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_CWSValidationResultFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionCWSDeserializationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_CWSDeserializationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionInvalidTokenFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_InvalidTokenFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionCWSInvalidServiceInformationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_CWSInvalidServiceInformationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        } catch (ICwsTransactionProcessingRequestTransactionCWSInvalidMessageFormatFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ICwsTransactionProcessing_RequestTransaction_CWSInvalidMessageFormatFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
