
package com.evosnap.schemas.cws.v2_0.dataservices.tms;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-22T08:24:52.604-07:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "TMSTransactionFailedFault", targetNamespace = "http://schemas.evosnap.com/CWS/v2.0/DataServices/TMS/Faults")
public class ITMSOperationsQueryRejectedSummaryTMSTransactionFailedFaultFaultFaultMessage extends Exception {
    
    private com.evosnap.schemas.cws.v2_0.dataservices.tms.faults.TMSTransactionFailedFault tmsTransactionFailedFault;

    public ITMSOperationsQueryRejectedSummaryTMSTransactionFailedFaultFaultFaultMessage() {
        super();
    }
    
    public ITMSOperationsQueryRejectedSummaryTMSTransactionFailedFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ITMSOperationsQueryRejectedSummaryTMSTransactionFailedFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ITMSOperationsQueryRejectedSummaryTMSTransactionFailedFaultFaultFaultMessage(String message, com.evosnap.schemas.cws.v2_0.dataservices.tms.faults.TMSTransactionFailedFault tmsTransactionFailedFault) {
        super(message);
        this.tmsTransactionFailedFault = tmsTransactionFailedFault;
    }

    public ITMSOperationsQueryRejectedSummaryTMSTransactionFailedFaultFaultFaultMessage(String message, com.evosnap.schemas.cws.v2_0.dataservices.tms.faults.TMSTransactionFailedFault tmsTransactionFailedFault, Throwable cause) {
        super(message, cause);
        this.tmsTransactionFailedFault = tmsTransactionFailedFault;
    }

    public com.evosnap.schemas.cws.v2_0.dataservices.tms.faults.TMSTransactionFailedFault getFaultInfo() {
        return this.tmsTransactionFailedFault;
    }
}
